import os
import json
import requests
from groq import Groq
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

API_BASE_URL = os.getenv("API_BASE_URL", "http://localhost:5001/students")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

if not GROQ_API_KEY or GROQ_API_KEY == "your_groq_api_key_here":
    print("❌ ERROR: Please set your GROQ_API_KEY in the python-agent/.env file.")
    exit(1)

# Configure Groq AI
client = Groq(api_key=GROQ_API_KEY)

# Use the latest model
model = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """
You are an intelligent assistant for a Student Management System.
Your job is to extract the user's intent and necessary entities from natural language to interact with a REST API.

Supported Intents:
- "ADD_STUDENT"
- "GET_STUDENT"
- "GET_ALL_STUDENTS"
- "UPDATE_STUDENT"
- "DELETE_STUDENT"
- "UNKNOWN" (if the user is asking something completely unrelated or ambiguous)

You MUST respond strictly in valid JSON format. Do not include Markdown blocks (like ```json), just output the raw JSON object.

Format for ADD_STUDENT:
{
  "intent": "ADD_STUDENT",
  "entities": {
    "studentId": "String (e.g. STU100, if not provided generate one randomly like S999)",
    "name": "String",
    "age": Number,
    "subjects": [{"subjectName": "String", "score": Number}]
  }
}

Format for GET_STUDENT, UPDATE_STUDENT, DELETE_STUDENT:
{
  "intent": "<INTENT>",
  "entities": {
    "studentId": "String"
  }
}
If it is UPDATE_STUDENT, also include the fields being updated in the entities.

Format for UNKNOWN:
{
  "intent": "UNKNOWN",
  "message": "String (explain why you couldn't understand or ask for clarification)"
}
"""

def process_intent(llm_response_json):
    """Executes the REST API calls based on the parsed intent."""
    try:
        data = json.loads(llm_response_json.strip())
        intent = data.get("intent")
        entities = data.get("entities", {})

        print(f"\n🤖 [AI Parsing Result] Intent: {intent}")
        print(f"📦 [Extracted Data] {json.dumps(entities, indent=2)}")

        if intent == "ADD_STUDENT":
            print(f"\n📡 Calling POST {API_BASE_URL}...")
            res = requests.post(API_BASE_URL, json=entities)
            if res.status_code == 201:
                return f"✅ Successfully added student {entities.get('name')} (ID: {res.json().get('studentId')})."
            else:
                return f"❌ Backend Error: {res.json().get('message', res.text)}"

        elif intent == "GET_STUDENT":
            student_id = entities.get("studentId")
            print(f"\n📡 Calling GET {API_BASE_URL}/{student_id}...")
            res = requests.get(f"{API_BASE_URL}/{student_id}")
            if res.status_code == 200:
                student = res.json()
                return (f"🎓 Found Student: {student['name']} (Age: {student['age']})\n"
                        f"📊 Average: {student['averageScore']:.1f}% | Grade: {student['grade']} "
                        f"| Status: {'Pass' if student['isPass'] else 'Fail'}")
            elif res.status_code == 404:
                return f"⚠️ Student {student_id} was not found."
            else:
                return f"❌ Backend Error: {res.text}"

        elif intent == "GET_ALL_STUDENTS":
            print(f"\n📡 Calling GET {API_BASE_URL}...")
            res = requests.get(API_BASE_URL)
            if res.status_code == 200:
                students = res.json()
                return f"📚 Found {len(students)} students in the database."
            else:
                return "❌ Failed to fetch students."

        elif intent == "DELETE_STUDENT":
            student_id = entities.get("studentId")
            print(f"\n📡 Calling DELETE {API_BASE_URL}/{student_id}...")
            res = requests.delete(f"{API_BASE_URL}/{student_id}")
            if res.status_code == 200:
                return f"🗑️ Student {student_id} was successfully deleted."
            elif res.status_code == 404:
                return f"⚠️ Student {student_id} was not found."
            else:
                return f"❌ Backend Error: {res.text}"

        elif intent == "UNKNOWN":
            return f"❓ {data.get('message', 'I am not sure what you want me to do.')}"
        
        else:
            return "❌ Unsupported intent generated by AI."

    except json.JSONDecodeError:
        return "❌ Error: AI did not return a valid JSON format."
    except requests.exceptions.ConnectionError:
        return "🔌 Error: Backend server is offline! Please ensure Node.js is running."
    except Exception as e:
        return f"❌ Unexpected Error: {str(e)}"

def run_chat():
    print("======================================================")
    print("🤖 Intelligent Student Management Agent (Type 'exit' to quit)")
    print("======================================================")
    
    while True:
        user_input = input("\nYou: ")
        if user_input.lower() in ['exit', 'quit']:
            print("Goodbye! 👋")
            break
            
        if not user_input.strip():
            continue

        try:
            # Ask Groq to parse the input
            prompt = f"{SYSTEM_PROMPT}\n\nUser Input: \"{user_input}\""
            response = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}]
            )
            
            raw_text = response.choices[0].message.content
            # Sometimes the model still wraps in markdown despite instructions, let's clean it
            if raw_text.startswith("```json"):
                raw_text = raw_text.replace("```json", "", 1).replace("```", "", 1)
            elif raw_text.startswith("```"):
                raw_text = raw_text.replace("```", "", 1).replace("```", "", 1)
                
            reply = process_intent(raw_text)
            print(f"\nAgent: {reply}")

        except Exception as e:
            print(f"\nAgent: ⚠️ An error occurred with the AI - {str(e)}")

if __name__ == "__main__":
    run_chat()
